// Generated by CoffeeScript 1.7.1
(function() {
  var Category;

  Category = require('./schema').Category;

  Category.validatesUniquenessOf('name');

  Category.validatesPresenceOf('name');

  module.exports = Category;

}).call(this);
