// Generated by CoffeeScript 1.7.1
(function() {
  var Config;

  Config = (function() {
    function Config() {}

    Config.host = "10.0.0.198";

    Config.username = function() {
      switch (process.env.NODE_ENV) {
        case 'production':
          return "proteus";
        case 'development':
          return 'proteus';
        case 'test':
          return 'proteus';
        default:
          return 'proteus';
      }
    };

    Config.password = function() {
      switch (process.env.NODE_ENV) {
        case 'production':
          return "u5bl4ck";
        case 'development':
          return 'u5bl4ck';
        case 'test':
          return 'u5bl4ck';
        default:
          return 'u5bl4ck';
      }
    };

    Config.db = function() {
      switch (process.env.NODE_ENV) {
        case 'production':
          return "kapiqua_" + process.env.NODE_ENV;
        case 'development':
          return "kapiqua_" + process.env.NODE_ENV;
        case 'test':
          return "kapiqua_" + process.env.NODE_ENV;
        default:
          return "kapiqua_development";
      }
    };

    Config.connection_string = "postgres://" + (Config.username()) + ":" + (Config.password()) + "@" + Config.host + "/" + (Config.db());

    return Config;

  })();

  module.exports = Config;

}).call(this);
