// Generated by CoffeeScript 1.8.0
(function() {
  var CartCoupon, CartCoupons;

  CartCoupon = require('../models/cart_coupon');

  CartCoupons = (function() {
    function CartCoupons() {}

    CartCoupons.create = function(data, respond, socket) {
      return CartCoupon.addCoupon(data, respond, socket);
    };

    CartCoupons.destroy = function(data, respond, socket) {
      return CartCoupon.removeCoupon(data, respond, socket);
    };

    return CartCoupons;

  })();

  module.exports = CartCoupons;

}).call(this);
